set PYO3_PYTHON C:\Python\Python38\python.exe
C:\Python\Python38\python setup.py bdist_wheel
set PYO3_PYTHON C:\Python\Python39\python.exe
C:\Python\Python39\python setup.py bdist_wheel
set PYO3_PYTHON C:\Python\Python310\python.exe
C:\Python\Python310\python setup.py bdist_wheel
set PYO3_PYTHON C:\Python\Python311\python.exe
C:\Python\Python311\python setup.py bdist_wheel
set PYO3_PYTHON C:\Python\Python312\python.exe
C:\Python\Python312\python setup.py bdist_wheel
set PYO3_PYTHON C:\Python\Python313\python.exe
C:\Python\Python313\python setup.py bdist_wheel